### ISSUE TITLE
How to install and run ?

### ISSUE THREAD

**Issue by papiche** [nyancodeid/insta-share#11]
My question might seem stupid, but I don't know much about node.js
I am using ipfs through CLI interface... I would like to test your app.

What is next after ```npm run build```?

Thanks

**Comment by nyancodeid** [comment]
To run this web app it should be `npm run serve`. And the web server should start at port `:5000`, you just need to open the url to your browser.

For now we are using the IPFS server provided by Infura.So we don't need Local IPFS node anymore. This is to make it simpler to use.
